home:
  path: /home
  controller: DevBodas\Dev\Infrastructure\EntryPoint\Controller\Homepage

#Controlers

post_simulator:
  path: /{version}/simulator
  controller: DevBodas\Dev\Infrastructure\EntryPoint\Controller\PostSimulator
  methods: POST
  requirements:
    version: v1
